### ISSUE TITLE
Implement form closing event handler for Create Message Window

### ISSUE THREAD

**Issue by umin18** [YongCho/MinimalEmailClient#27]
Email headers and message body still intact when reopening the create message window.

**Comment by YongCho** [comment]
You can reset them in UserControl.Loaded event handler.

**Comment by umin18** [comment]
ahh yes, the UserControl.Loaded handler.  You are a dear Mr. Cho.

**Comment by umin18** [comment]
3eb1e06c3230298f4895dbc3e3ad301e608b4a0f
