### ISSUE TITLE
Enable Multipart sender to write HTML Emails

### ISSUE THREAD

**Issue by umin18** [YongCho/MinimalEmailClient#41]
Multipart sender should allow user to send email in HTML format.

**Comment by umin18** [comment]
WPF does not offer a control which allows editing of HTML content.  This issue may be more intensive than anticipated.  This issue may require a workaround, or plugin that offers this feature.

**Comment by YongCho** [comment]
HTML editor is large enough to be a project of its own. I don't think any framework would offer it as a standard control. I think this issue might take a little longer than the time we want to spend. If you still want to go for it, I came across some 3rd-party solutions.
- [Smith Html Editor](http://smithhtmleditor.codeplex.com/)
- [Bindable WPF RichText Editor with XAML/HTML Convertor](http://michaelsync.net/2009/06/09/bindable-wpf-richtext-editor-with-xamlhtml-convertor)
- [C# WPF WYSIWYG HTML Editor](http://www.codeproject.com/Tips/870549/Csharp-WPF-WYSIWYG-HTML-Editor)

**Comment by umin18** [comment]
I will test some of these 3rd party solutions, they may offer the type of control we need for editing and sending html messages.
