### ISSUE TITLE
Program crashes sometimes when clicking 'Reply' button.

### ISSUE THREAD

**Issue by YongCho** [YongCho/MinimalEmailClient#45]
When clicking 'Reply' button, program sometimes terminates with System.IndexOutOfRangeException.

**Comment by umin18** [comment]
If this bug is related to my reply implementation, I can take a look at it when I have time after work this week.

**Comment by umin18** [comment]
Could you give me an example of how I might be able to replicate this issue?

**Comment by YongCho** [comment]
I haven't looked into this yet. All I know is that it only happens once a while, and when it happens, the program crashes as soon as I hit the reply button (even before the reply window opens).

**Comment by YongCho** [comment]
The problem seems to be where you parse the sender email address. Below code can throw an IndexOutOfRange exception if Sender string does not contain '<', '>' characters which I believe is the case sometimes.

```
Sender.Split('<', '>')[1]
```

**Comment by YongCho** [comment]
Ok. I see how you tried to solve the issue by filtering the domain suffixes. However, this approach could be problematic. There are numerous domain names out there that do not end with the 7 top level domains (@SomeBusiness.biz, @SomeOrganization.or.kr to name a few I found in my inbox). Your implementaion will not work on them.

**Comment by YongCho** [comment]
Also, I am moving all these codes to NewEmailViewModel since that's where they belong conceptually - a11900bae93f4c7f243b48b5c240e1b4a0bb4fcc.

**Comment by umin18** [comment]
I implemented a fix for the most common top level domain suffixes.  I only have two hours approximately on a nightly basis so I structured a basic implementation for now.  There are over 1000 top level domains in existence.  I'm going to be working on a more fully functional domain parser when I get home.  There is nothing wrong with the reply as it right now, the only issue is that our email client will not respond to email domains out of country.  Please worry about your side of the project and I will test and debug my program as we progress.  If something doesn't work it is easier to remove the functionality if it has any major issues before presentation.

**Comment by YongCho** [comment]
I'm just trying to bug you, that's all :stuck_out_tongue:

**Comment by YongCho** [comment]
By the way, if you are trying to extract an email address, wouldn't it be easier to just regex match www@xxx.yyy or www@xxx.yyy.zzz instead of implementing a full list of domain names?
