### ISSUE TITLE
Move 'Favorites' out of Account model.

### ISSUE THREAD

**Issue by YongCho** [YongCho/MinimalEmailClient#51]
Although a 'favorite recipient list' may be associated to each sender email address, it is a purely local implementation and not part of an IMAP/SMTP information. Therefore, it should not reside in the IMAP/SMTP Account model and should be managed separately. Spend some time to design this carefully so it does not mingle with the existing codes and can be developed modularly.

**Comment by YongCho** [comment]
By the way, we are now approaching the final stage of the project. I understand you want to implement new features, but I think we should focus more on making the existing features work reliably. When you implement new features, please design it carefully and also take some time to test your codes before making a commit so it doesn't result in additional debugging/correcting effort.

**Comment by umin18** [comment]
Each account can have its own list of favorites.  I'm not incorporating a global favorites list because I personally would not want all of my email accounts to share all the same contacts.

**Comment by umin18** [comment]
If you want the contacts list out of Account, I'll just create a separate model for it and associate the the favorites list on a per user basis.

**Comment by YongCho** [comment]
That would be a better way to approach it. I'm closing this issue because I have a feeling it is closely related to #50.
