### ISSUE TITLE
Reply and Forwarding methods do not pass attachments to WriteNewMessageNotification if the email has been pre-loaded

### ISSUE THREAD

**Issue by umin18** [YongCho/MinimalEmailClient#56]
When passing savedAttachments to WriteNewMessageNotification from a pre-loaded email, the list is empty.  Is there a way we can load the savedAttachments before sending this parameter to the WriteNewMessageNotification?

**Comment by YongCho** [comment]
'savedAttachments' is pupulated when the email body is finished being downloaded. Before that, it is not populated. By 'pre-loaded email' do you mean an email whose body has been downloaded already? If that's the case, 'savedAttachments' is populated as soon as you open the MessageContentView window. If that's not the case, then it is populated a couple of seconds later when the email body is fully downloaded.

**Comment by YongCho** [comment]
In short, if you see the message body showing up on MessageContentView window, you can assume 'savedAttachments' is populated.
